@usersp = http://localhost:3000/user/usersp
@login = http://localhost:3000/user/login
@saveMarker = http://localhost:3000/user/saveMarker
@deleteMarker = http://localhost:3000/user/deleteMarker
@linkMarker = http://localhost:3000/user/linkMarker
@taskUpload = http://localhost:3000/user/taskUpload
@taskDelete = http://localhost:3000/user/taskDelete
@getMarkers = http://localhost:3000/user/getMarkers

POST {{login}}
Content-Type: application/json

{
    "email" : "goran@email",
    "password" : "4321"
}

###
POST {{usersp}}
#header
Content-Type: application/json
#body

{
    "email" : "goran@email",
    "nombre" : "Goran",
    "password" : "4321"
}

###
POST {{saveMarker}}
#header
Content-Type: application/json
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNzI4NjY5ODYxLCJleHAiOjMuNmUrMzB9.wtpa86BtgJnZ_EVppj1Ltz7GlI_X6Ih4FxGmr1q2RVo
#body

{
    "nombre" : "Register",
    "link" : "/LoginScreen"
}

###
POST {{deleteMarker}}
#header
Content-Type: application/json
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNzI4NjY5ODYxLCJleHAiOjMuNmUrMzB9.wtpa86BtgJnZ_EVppj1Ltz7GlI_X6Ih4FxGmr1q2RVo
#body

{
    "markerId" : "4"    
}

###
POST {{linkMarker}}
#header
Content-Type: application/json
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNzI4NjY5ODYxLCJleHAiOjMuNmUrMzB9.wtpa86BtgJnZ_EVppj1Ltz7GlI_X6Ih4FxGmr1q2RVo
#body

{
    "markerId" : "9"
}

###
POST {{taskUpload}}
#header
Content-Type: application/json
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNzI5OTEzMDk4LCJleHAiOjE3MzExMjI2OTh9.23agkfm7FwqjAmyUNHKxE6wMSUSI0FGw4rZw0fZC4ow
#body

{
    "title" : "Tarea 2",
    "content" : "lorem"
}

###
POST {{taskDelete}}
#header
Content-Type: application/json
auth : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdvcmFuQGVtYWlsIiwiaWF0IjoxNzI5OTEzMjQ0LCJleHAiOjE3MzExMjI4NDR9.BPPlzZLE1d7JK3XQwgDFzRHZ8lVh2usAk-xaSFqwBRM
#body

{
    "idTask" : "4"
}

###
GET {{getMarkers}}
#header
Content-Type: application/json
auth: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluIiwiaWF0IjoxNzI5MDgyMzIxLCJleHAiOjE3MzAyOTE5MjF9.c-umqzl99Rxnq_hMBVdsbt6YOXbU4gKCXCI78Xw_NHs
#body

{
    "email" : "admin"
}